### ISSUE TITLE
Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by stuartleeks** [ashleyschuett/kubeconfig-cleanup#4]
I just discovered this project and am keen to give it a try. I followed the instructions in the README to clone the repo into the `.kube/plugins/kubeconfig-cleanup` folder but I get the following error when I try to run it:

```
 $ kubectl plugin kubeconfig-cleanup
error: fork/exec ./cleanup: exec format error
```

I also tried to grab the source with `go get` but get an error with that too:

```
# github.com/ashleyschuett/kubeconfig-cleanup/pkg/config
pkg/config/config.go:164:52: cannot use m.getContextsUser(context) (type *"k8s.io/client-go/tools/clientcmd/api".AuthInfo) as type *"k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/api".AuthInfo in assignment
pkg/config/config.go:166:118: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions in argument to client.CoreV1().ConfigMaps("k8s.io/apimachinery/pkg/apis/meta/v1".NamespacePublic).Get
```

Any suggestions? :-)

**Comment by ashleyschuett** [comment]
That's because the binary in the repo was built for macOS. You'll have to build it for linux using `CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cleanup`. The type errors look like the dependancies where installed incorrectly. They should be fixed by running `glide install -v`

Let me know if those fixes help you or if there are more errors. I'm working on making this more user friendly.

**Comment by ashleyschuett** [comment]
You should now be able to get the correct release binary from https://github.com/ashleyschuett/kubeconfig-cleanup/releases/tag/v1.0.1

The read me is updated as well, if you are still having this issue feel free to reopen the issue, or create a new one.
